# Possible layout values: top-right, left, right, list
# Site
repository: phemasundar/phemasundar.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: HemaSundar Penugonda
title: Principal Consultant
email: p.hemasundar@gmail.com
# email_title: Email (Email title override)
phone: +91-8867 773565
# phone_title: Phone (Phone title override)
website: https://stlcpro.com
website_title: Blog
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: phemasundar
github_username: phemasundar
stackoverflow_username: "2377561"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: hemasundarpenugonda
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_0995_1_500x506_100.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an Automation test Engineer with 12 years of experience in <mark>Functional testing</mark>. I have helped companies release their products by assuring them of better quality.
                 
  Some examples include
    - As a test engineer at Trivium, I have introduced test automation into the team by using Selenium & JAVA. Automated most of the repeated tasks like creating Test users creation, Sanity tests, Creating Test data, etc...
    - As a senior consultant at Xebia, I have helped multiple clients by implementing functional UI automation tests for browsers & mobile apps by using tools Selenium & Appium.
    - As a lead consultant in Xebia, I have helped clients with their Testing process assessment, thereby the betterment of their testing process.
    - Delivered multiple projects in Test lead role.
    - Have good experience in creating CI pipelines using Jenkins & Azure DevOps
  
  I get excited about opportunities where I get to improve myself by learning new things & to work in a good team environment.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Store Colleague Experience
        link: https://github.com/phemasundar/test-automation-core
        link_text: Parent Repo
        additional_links:
          - title:  Native Mobile App Automation
            icon: fab fa-github
            url: https://github.com/phemasundar/test-automation-native-mobile
          - title:  Web App Automation
            icon: fab fa-github
            url: https://github.com/phemasundar/test-automation-desktop-web
          - title:  API Automation
            icon: fab fa-github
            url: https://github.com/phemasundar/test-automation-api
        quote: >
          Retail Store colleague experience project helps the Store colleagues (Store managers and on-ground staff) to minimize their manual effort in keeping track of the stock. It has multiple modules like maintaining the current stock numbers, stock to be imported, Information of discounts on items, maintaining the wastage, etc. As a functional automation tester, our job is to make sure that all the modules of the project are working fine with all different sets of data (store items) and can pass the info in between the modules.
        description: | # this will include new lines to allow paragraphs
          - Used **Appium & Cucumber** to perform **Functional Testing & Regression & Retesting**.
          - Build development CI pipeline using CICD tool **Jenkins** with **Git**
          - Implemented **Hybrid Framework** with **Cucumber & TestNG**.
          - Responsible for configuring & scheduling Jenkins jobs for executing test cases at regular intervals and nightly builds.
          - Involved in **Kick-off meetings** with client to gather requirement.
          - Involved in Sprint planning and prepared Test estimates.
          - Understanding the Requirements and Functional Specifications of the application.
          - Prepared & executed test cases and reported the results.
          - Used **JIRA** for issue tracking.
          - Involved in Review the Test Cases (Peer Review).
          - Involved in daily stand-up meetings with onsite team members.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Xebia IT Architects
        sub_title: Principal Consultant
        caption: March 2015 - present
        link: https://xebia.com/
        quote:
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: left
        title: Trivium eSolutions
        sub_title: Senior Software Test Engineer
        caption: October 2012 - February 2015
        link: https://trivium-esolutions.com/
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Technology
        sub_title: Electronics & Communications Engineering (ECE)
        caption: 2005 - 2009
        quote: >
          Jawaharlal Nehru Technological University (JNTU), Kakinada
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
